services:
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: personal-site-dev
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: personal-site-prod
    ports:
      - 3001: 3000
    volumes:
      - .:/app
